// Auto-generated by rebuild-camp-taylor.py — do not edit by hand.
export type TimelinePhoto = { src: string; width: number; height: number; alt: string; caption: string }

export const timelinePhotos: TimelinePhoto[] = [
  { src: "/projects/camp-taylor/timeline-01.jpg", width: 1920, height: 1080, alt: "Camp Taylor — Sep 2024", caption: "Sep 2024" },
  { src: "/projects/camp-taylor/timeline-02.jpg", width: 1920, height: 1080, alt: "Camp Taylor — Oct 2024", caption: "Oct 2024" },
  { src: "/projects/camp-taylor/timeline-03.jpg", width: 1920, height: 1080, alt: "Camp Taylor — Nov 2024", caption: "Nov 2024" },
  { src: "/projects/camp-taylor/timeline-04.jpg", width: 1920, height: 1080, alt: "Camp Taylor — Jan 2025", caption: "Jan 2025" },
  { src: "/projects/camp-taylor/timeline-05.jpg", width: 1920, height: 1080, alt: "Camp Taylor — Mar 2025", caption: "Mar 2025" },
  { src: "/projects/camp-taylor/timeline-06.jpg", width: 1920, height: 1080, alt: "Camp Taylor — Apr 2025", caption: "Apr 2025" },
  { src: "/projects/camp-taylor/timeline-07.jpg", width: 1920, height: 1080, alt: "Camp Taylor — Apr 2025", caption: "Apr 2025" },
  { src: "/projects/camp-taylor/timeline-08.jpg", width: 1920, height: 1080, alt: "Camp Taylor — Apr 2025", caption: "Apr 2025" },
  { src: "/projects/camp-taylor/timeline-09.jpg", width: 1920, height: 1080, alt: "Camp Taylor — Oct 2025", caption: "Oct 2025" },
  { src: "/projects/camp-taylor/timeline-10.jpg", width: 1920, height: 1080, alt: "Camp Taylor — Apr 2026", caption: "Apr 2026" },
  { src: "/projects/camp-taylor/timeline-11.jpg", width: 1920, height: 1080, alt: "Camp Taylor — Apr 2026", caption: "Apr 2026" },
  { src: "/projects/camp-taylor/timeline-12.jpg", width: 1920, height: 1080, alt: "Camp Taylor — Apr 2026", caption: "Apr 2026" },
]
