"""
Build a chronological "Project Timeline" gallery for Camp Taylor by sampling
12 photos evenly across the source folder (Sep 2024 -> Apr 2026). Output to
public/projects/camp-taylor/ as timeline-NN.jpg with EXIF orientation baked.

Doesn't touch the existing named files (night-pour-hero, finished-pool, etc.).

  Source:  Camp Taylor/*.{jpg,jpeg,png}
  Output:  portfolio-site/public/projects/camp-taylor/timeline-NN.jpg
           portfolio-site/src/app/projects/camp-taylor-pool/timeline-photos.ts
"""
import sys
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import re
from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(r"C:\Users\msgoo\Miles Construction Project Folder")
SRC = ROOT / "Camp Taylor"
OUT_DIR = ROOT / "portfolio-site" / "public" / "projects" / "camp-taylor"
TS_OUT = ROOT / "portfolio-site" / "src" / "app" / "projects" / "camp-taylor-pool" / "timeline-photos.ts"

COUNT = 12
MAX_DIM = 1920
QUALITY = 82

def list_sorted(folder: Path) -> list[Path]:
    # iOS timestamp-named photos only (skip image0/image1/etc. — renders/stock)
    files = [p for p in folder.iterdir()
             if p.is_file()
             and p.suffix.lower() in {".jpg", ".jpeg", ".png"}
             and re.match(r"\d{8}_\d", p.name)]
    return sorted(files, key=lambda p: p.name.lower())

def even_sample(files, n):
    if len(files) <= n:
        return files
    step = (len(files) - 1) / (n - 1)
    return [files[round(i * step)] for i in range(n)]

def process(src: Path, dst: Path) -> tuple[int, int]:
    with Image.open(src) as img:
        img = ImageOps.exif_transpose(img)
        if img.mode != "RGB":
            if img.mode in ("RGBA", "LA", "P"):
                bg = Image.new("RGB", img.size, (255, 255, 255))
                if img.mode == "P":
                    img = img.convert("RGBA")
                bg.paste(img, mask=img.split()[-1] if img.mode in ("RGBA", "LA") else None)
                img = bg
            else:
                img = img.convert("RGB")
        w, h = img.size
        if max(w, h) > MAX_DIM:
            r = MAX_DIM / max(w, h)
            img = img.resize((int(w*r), int(h*r)), Image.LANCZOS)
            w, h = img.size
        img.save(dst, "JPEG", quality=QUALITY, optimize=True)
    return w, h

def caption(p: Path) -> str:
    """Make a human-friendly caption from iOS timestamped filename."""
    m = re.match(r"(\d{4})(\d{2})(\d{2})", p.name)
    if not m: return p.stem
    months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
    return f"{months[int(m.group(2))-1]} {m.group(1)}"

def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for f in OUT_DIR.glob("timeline-*.jpg"):
        f.unlink()

    pool = list_sorted(SRC)
    picks = even_sample(pool, COUNT)
    out = []
    for i, src in enumerate(picks, 1):
        name = f"timeline-{i:02d}.jpg"
        w, h = process(src, OUT_DIR / name)
        cap = caption(src)
        out.append({"src": f"/projects/camp-taylor/{name}",
                    "width": w, "height": h,
                    "alt": f"Camp Taylor — {cap}",
                    "caption": cap})
        print(f"  timeline {i:02d}: {src.name} -> {w}x{h} ({cap})")

    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(
        f'  {{ src: "{p["src"]}", width: {p["width"]}, height: {p["height"]}, '
        f'alt: "{p["alt"]}", caption: "{p["caption"]}" }},'
        for p in out
    )
    ts = (
        "// Auto-generated by rebuild-camp-taylor.py — do not edit by hand.\n"
        "export type TimelinePhoto = { src: string; width: number; height: number; "
        "alt: string; caption: string }\n\n"
        "export const timelinePhotos: TimelinePhoto[] = [\n"
        f"{body}\n"
        "]\n"
    )
    TS_OUT.write_text(ts, encoding="utf-8")
    print(f"\nWrote {TS_OUT.relative_to(ROOT)} ({len(out)} photos)")

if __name__ == "__main__":
    main()
